version: "3.8"
services:
  backend:
    build: .
    container_name: workoutbuddy-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - workoutbuddy_data:/app/instance
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: workoutbuddy-frontend
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./app.js:/usr/share/nginx/html/app.js:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  workoutbuddy_data:



